- name: Install nginx
  apt: name=nginx state=latest

- name: Install letsencrypt
  apt: name=letsencrypt state=latest update_cache=yes

- name: Create letsencrypt directory
  file: name=/var/www/letsencrypt state=directory

- name: Remove default nginx config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Install nginx site for letsencrypt requests
  template:
    src: nginx-http.j2
    dest: /etc/nginx/sites-enabled/http

- name: Reload nginx to activate letsencrypt site
  service: name=nginx state=restarted

- name: Create letsencrypt certificate for bitwarden
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ LETSENCRYPT_MAIL }} --agree-tos -d {{ BITWARDEN_DOMAIN_NAME }}
  args:
    creates: /etc/letsencrypt/live/{{ BITWARDEN_DOMAIN_NAME }}
  when: BITWARDEN_DOMAIN_NAME is defined

- name: Create letsencrypt certificate for nextcloud
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ LETSENCRYPT_MAIL }} --agree-tos -d {{ NEXTCLOUD_DOMAIN_NAME }}
  args:
    creates: /etc/letsencrypt/live/{{ NEXTCLOUD_DOMAIN_NAME }}
  when: NEXTCLOUD_DOMAIN_NAME is defined

- name: Create letsencrypt certificate for other services
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ LETSENCRYPT_MAIL }} --agree-tos -d {{ OTHER_DOMAIN_NAME }}
  args:
    creates: /etc/letsencrypt/live/{{ OTHER_DOMAIN_NAME }}
  when: OTHER_DOMAIN_NAME is defined

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Install nginx site for {{ BITWARDEN_DOMAIN_NAME }}
  template:
    src: nginx-https-bitwarden.j2
    dest: /etc/nginx/sites-enabled/{{ BITWARDEN_DOMAIN_NAME }}
  when: BITWARDEN_DOMAIN_NAME is defined

- name: Install nginx site for {{ NEXTCLOUD_DOMAIN_NAME }}
  template:
    src: nginx-https-nextcloud.j2
    dest: /etc/nginx/sites-enabled/{{ NEXTCLOUD_DOMAIN_NAME }}
  when: NEXTCLOUD_DOMAIN_NAME is defined

- name: Install nginx site for {{ OTHER_DOMAIN_NAME }}
  template:
    src: nginx-https-other.j2
    dest: /etc/nginx/sites-enabled/{{ OTHER_DOMAIN_NAME }}
  when: OTHER_DOMAIN_NAME is defined

- name: Reload nginx to activate specified site
  service: name=nginx state=restarted

- name: Add letsencrypt cronjob for cert renewal 1
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ LETSENCRYPT_MAIL }} --agree-tos -d {{ BITWARDEN_DOMAIN_NAME }} && service nginx reload
  when: BITWARDEN_DOMAIN_NAME is defined

- name: Add letsencrypt cronjob for cert renewal 2
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ LETSENCRYPT_MAIL }} --agree-tos -d {{ NEXTCLOUD_DOMAIN_NAME }} && service nginx reload
  when: NEXTCLOUD_DOMAIN_NAME is defined

- name: Add letsencrypt cronjob for cert renewal 3
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ LETSENCRYPT_MAIL }} --agree-tos -d {{ OTHER_DOMAIN_NAME }} && service nginx reload
  when: OTHER_DOMAIN_NAME is defined
